apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-server
    spec:
      containers:
        - image: pplevins/mongo_api_server
          name: mongo-server
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_URL
          ports:
            - containerPort: 8000
              name: mongo-server