apiVersion: v1
kind: Service
metadata:
  name: mongo-server
  namespace: pplevins-dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30009
  selector:
    app: mongo-server