apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: pplevins-dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32701
  selector:
    app: mongo